name: Deploy MkDocs

on:
  push:
    branches: [master, main, feature-multline-block]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'CNAME'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          pip install mkdocs-material
          pip install mkdocs-static-i18n
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - run: mkdocs gh-deploy --force